<?php
// require_once("maintenance.php");
// maintenance(TRUE);
include_once "config/database.php"; 
include_once "object/login.php";
 $database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'AboutUs' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
    
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />


<title><?php echo $title; ?></title>

<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />    

<!--<meta name="description" content="Enjoy Fast Access To Top Family Lawyers Across The US. Connect Now With An Attorney In Your Local Area And Get Your Questions Answered Now.">-->
<?php echo "<meta name='description' content='$meta_desc'>"?>

<!--yandex-->
<meta name="yandex-verification" content="0beccc11dc0dc9cb" />

<?php include "libs.php"; ?>



<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "About Us",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Who We Are",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>
</head>

<body class="bg-white fontb">
<?php include_once "header.php" ?>

<div class="jumbotron jumbotron-fluid bg1 about_bg border-0">
    <div class="paddings">
        <h1 class="size46 text-white text-center">ABOUT US</h1>
    </div>
</div>

<div class="container-fluid pt-5 pb-5 pr-0 pl-0 m-0 row">

    <div class="col-lg-7 col-md-7 col-sm-12 col-12 ">
        <h2 class=" text-dark font-weight-bold" style="padding-left:30px;">Who We Are</h2>
        <p class="font-weight-normal text-secondary p-4 text-justify size15 decor">
            Affordable Legal Help is a legal assistance company dedicated to providing you with low-cost and high-quality legal services. We have been in the business since 2006 and have got many feathers in our cap.<br /><br />
    
    Our specialization is <b class="font-weight-bold" >UNBUNDLED LEGAL SERVICE</b>, an innovative concept in the field of the judicial process. In this system, an attorney does not provide complete services to their clients, but instead supports the client’ only when needed. The client can handle the rest of the case by his or her  accord.<br /><br />
    
    This concept has not only opened a new niche in legal service, but also eased up the process of legal proceedings by bringing   <b  class="font-weight-bold" >AFFORDABLE LEGAL HELP</b> to the table. Unbundled legal service is applicable across categories, but in our case, we have combined it with one of the most difficult and poignant tiers of legal cases: family cases.  Family cases occupy the second spot after criminal cases in America, demonstrating how challenging and fragile handling these issues have become.<br /><br />
    
    Our attorneys are well-experienced professionals who have worked for an extensive period of time in family courts, handling a range of cases pertaining to family matters such as child support, custody, divorce and grandparent access to children. Their experience and professional insight have helped hundreds of clients over the span of 13 years to get a satisfactory closure to the pivotal matters of their life.<br /><br />
    
    We believe that in order to sort out familial matters legally, one should not have to monetarily drain themselves as well as emotionally. The basic principle underlying our company is providing high-quality services at affordable rates.<br /><br />
        </p>
    </div>
    
    
    <div class="col-lg-5 col-md-5 col-sm-12 col-12  text-center">
    <div class="ser_border pr-0 mr-0">
        <div class="d-block m-auto "><h2 class="font-weight-bold">Mission & Vision</h2></div>
        <hr />
        <div class="">
            <h4 class="font-weight-bold text-dark">Our Vision</h4>
            <p class="container text-secondary text-center font-weight-normal text-justify size15 decor">
            	The company envisions spreading more awareness about unbundled legal services. We believe in creating a new niche in legal services that will benefit the needy and bring down the overall expenses in the field. So far, we have been able to reach a level where we have contributed significantly to the creation of this new niche. Our growing number of clients and their positive responses are a testament to this fact..
            </p>
     	</div>
        <div class="">
            <h4 class=" font-weight-bold text-dark">Our Mission</h4>
            <p class="container text-secondary text-center font-weight-normal text-justify size15 decor">
            	We strive to become the leading unbundled legal services company in the United States. Thanks to the growing awareness about unbundled legal services, we see ourselve reaching this level of success in a substantial period. Our goal is to be known as the most reliable organization that provides high-quality and affordable legal services to anyone in need of help. We hope that our labor will bear fruits of success not just for us, but also for the niche.
             </p>
     	</div>
        <div class="">
            <h4 class=" font-weight-bold text-dark">Our Values</h4>
            <p class="container text-secondary text-center font-weight-normal text-justify size15 decor">
            	Our guiding principles every day are integrity, honesty and hard work. Ours success with numerous cases has only further strengthened our belief in these core principles. We value honesty and transparency with our clients and the system as well as diligence when it comes to our share of the work.
             </p>
     	</div>
    </div>
    </div>
    
</div>


<?php include_once "footer.php" ?>




<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<?php include "libs2.php"; ?>







</body>
</html>