<?php include_once "config/database.php"; 
$database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'blogpages' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transition .dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
<meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<base href="https://affordablelegalhelp.com/blog_pages.php">
<title><?php echo $title; ?> </title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<?php echo "<meta name='description' content='$meta_desc'>"?>


<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">

<?php include "libs.php"; ?>


<style>
@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap');

.font_meri{
  font-family: 'Merriweather', serif;
  color: rgb(0, 83, 163);
  font-weight: 200;
}
</style>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>

</head>

<body class="bg33">
<div id="fb-root"></div>
<!--<script -->
<!--async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0">-->
<!--</script>-->


<?php include"header.php"; ?>

<div class="jumbotron jumbotron-fluid bg1 blog_bg border-0">
    <div class="paddings">
        <h1 class="size46 text-white text-center ">OUR BLOGS</h1>
    </div>
</div>



<section class="container text-left text-dark mt-5">
    <div class="row">
    		
        <div class="col-lg-8 col-md-12 col-sm-12 col-12 d-block">

			<div id="main_content" class="mb-5 mt-3">
				<?php 
				include("config/connect.php");

				if(isset($_GET['id'])){

				$page_id = $_GET['id'];

					$select_query = "select * from posts where post_url='$page_id'";

				$run_query = mysqli_query($con,$select_query);

				while($row=mysqli_fetch_array($run_query)){

					$post_id = $row['post_id']; 
					
                    $post_url = $row['post_url'];
					$post_title = $row['post_title'];
					$post_date = $row['post_date'];
					$post_author = $row['post_author'];
					$post_image = $row['post_image'];
					$post_content =$row['post_content'];
					
					
                    $arr = explode('-', $post_date);
                    $post_date = $arr[2].'-'.$arr[0].'-'.$arr[1];
				?>
				
				
				
				<img src="/images/<?php echo $post_image; ?>" class="img-fluid images" />

                <h2 class="font_meri mt-5"><?php echo $post_title; ?></h2>
                
                <p class="text-dark text-left font-weight-normal mb-3 mt-4">
                  <span class="text-primary"><?php echo $post_author; ?></span> |  <?php echo date("M d, Y", strtotime($post_date));?>
                </p>

                <hr class="mb-5">

                <?php 
                    // $post_content=strip_tags($post_content);
                    echo $post_content ;
                ?>

				<?php } }?>
				
				<!--<h3 class="mt-5">Comments:</h3>-->
				<!--<hr style="border-top: 3px solid rgb(84, 84, 86);">-->
				<!--<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-width="" data-numposts="5">-->
				<!--</div>-->
			</div>
		</div>

    	<div class="col-xl-4 col-lg-4 col-md-4 mb-5 mt-2 col-sm-12 col-12">
    
            <div class="card  bg-white set_img  card h-100  shadow rounded-0 pb-5" style="display: table-cell;">
                <div class="card-body text-dark">
                
                    <h6 class="font-weight-bold mb-5 mt-3">Recently Uploaded</h6>
                    <?php 
                    
                    $query = "select * from posts order by 1 DESC LIMIT 0,6";
                    
                        $run = mysqli_query($con,$query); 
                        
                        while ($row=mysqli_fetch_array($run)){
                        
                        $post_id = $row['post_id'];
                        
                        $post_url = $row['post_url'];
                        $title = $row['post_title'];
                        $post_date = $row['post_date'];
                        
                        
                        $arr = explode('-', $post_date);
                        $post_date = $arr[2].'-'.$arr[0].'-'.$arr[1];
                    
                    ?>
            
                    <div class="">
                      <!-- <a href="/<?php echo $post_url; ?>" class="col-5 d-block mr-0 pr-0">
                      <img src='images/<?php //echo $image; ?>' width='100' height='100'></a> -->
                      
                      <a href="/<?php echo $post_url; ?>" class="blog_hov1 d-block nav-link p-0 " >
                          <h6 class="font-weight-bold m-0" >
                              <?php echo $title; ?>
                          </h6>
                      </a>
            
                      <p class="text-black-50 text-left font-weight-bold pt-1">
                          <?php echo date("M d, Y", strtotime($post_date));?>
                      </p>
                      
                    </div>
                          
                    <?php } ?>
                
                </div>
            </div>
        </div>
            
	
	</div>
</section>

<?php include"footer.php"; ?>




<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<script defer src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php include "libs2.php"; ?>




</body>
</html>
