<?php 
// require_once("maintenance.php");
// maintenance(TRUE);


session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";

 $database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'childadoption' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title><?php echo $title ?></title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<?php echo "<meta name='description' content='$meta_desc'>"?>

<!--yandex-->
<meta name="yandex-verification" content="0beccc11dc0dc9cb" />

<?php include "libs.php"; ?>

<style>

ul {
    margin-top: 0px;
    margin-bottom: 1rem;
    background-color: white;
}


li {
    border-bottom: 1px solid rgba(39, 40, 41, 0.2);
    padding: 20px;
}

li:hover {
    background-color:white;
}

.paddings{
    padding-top:90px; 
    padding-bottom:90px;
}

.pos-abs{
    position: absolute !important; 
    width:100%; 
}

.pos-inh{
    position: inherit !important;
}

.l-h{
    line-height: 0.9;
}

.connect-btn{
    padding: 22px !important;
}

.height11{
    height:300px;
}
</style>





<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>

</head>




<body id="fill" class="fontb">
    
<div class="sticky-top mb-1">
<div class="alert bg-info alert-dismissible  rounded-0 border-0 m-0 p-0">
    <button type="button" class="close text-white mt-0 pt-1" data-dismiss="alert">&times;</button>
    <p class="size14 text-white text-center pt-2 pb-2 pr-5 pl-2 mb-0">COVID-19 UPDATE: Law firms are still available to help. Set up a consultation from home today.</p>
</div>
</div>


<?php include_once "header.php"; ?>


<?php if(isset($_REQUEST['submitbtn']))
{
}?>

<section class="adoption_bg bg2">
    <div class="container-fluid home_padding"><!--div 0 -->
    	<br />
        <h1 class="text-white  text-center jl_heading  font5">Find The Right Child Adoption Lawyer In Your Zip Code</h1>
        
        <p class=" texts text-white text-center">Rectify your child adoption issues for as low as  1000$ to 1250$,Receive an Immediate free consultation and Payment plans are also availaible.</p>
        
        <?php 
        	if (isset($_POST['submitbtn'])){}
        ?>
        
        <br>
        <form class="ser_state888 mt-3 centre" method="post" ><!--form a -->
        
            <div class="col-9 pr-0 pl-0"><!--div a -->
            	
            	<div class="row">
                
                    <div class="col-12 col-lg-8 col-md-8 col-sm-12 pr-0 pl-0">
                        <input type="text" name="country" id="country" class="form-control font-weight-normal texts rounded-0 ser_box mt-2"  placeholder="Enter Your City Or Zipcode" autocomplete="off"/>
                        
                        <div class="pos-abs" >
                        <div id="countryList" class="texts text-dark font-weight-normal text-left bg-transparent l-h" >
                        
                        </div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-lg-4 col-md-4 col-sm-12 pl-0 pr-0 pos-inh">
                        <div  id="btnconnect"><!--div c -->
                            <input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn btn-danger btn-block connect-btn rounded-0 mt-2"/>
                        </div><!--div c -->
                    </div>

                    <?php
 if (isset($_POST['submitbtn'])){
    $_SESSION['city']=$_POST['country'];
    $i=$_SESSION['city'];
    
    $_SESSION['from_page']="Child adoption";
    
    
    //$city1=$_POST['city'];
    $city_state = explode(",", $i);
    $query="SELECT * FROM `city` WHERE `City`='$city_state[0]' AND `State`='$city_state[1]' limit 1";
    $qu= $db->prepare($query);
    $qu->execute();
    $resultt=$qu->fetchAll(PDO::FETCH_OBJ);
    $row = $qu->fetch(PDO::FETCH_ASSOC);
    //$result=mysqli_query($conn,$query);
    //$check=mysqli_num_rows($result);
    
    // if($qu->rowCount() > 0){
    echo "<script type='text/javascript'> document.location = '/Complete-your-request'; </script>";	
    // }
    // else{
        
    //     echo "<script type='text/javascript'>$('#country').css({'border':'1px solid red'});</script>";
    //     echo "<span style='font-size:13px; color:#900;' class='error ml-5'>please enter valid US city</span>";
        
    // }
  }
?>
                    
                </div>
                
                
            </div><!--div a -->
                
                
                
                
        </form><!--form a -->
         
    </div><!--div 0 -->
    
</section>







<section class="container mt-5 pb-5">

    <h1 class="text-dark pt-4 font-weight-normal mb-3 size46" >Child Adoption</h1>
    <p class=" text-secondary  decor size15" >
        Adoption usually leaves couples with as much joy as birthing kids of their own. Also, there is a 
        sense of satisfaction and fulfillment that comes with knowing that you’ll be changing the life of 
        an orphan. <br>
        American legal system has put measures and benchmarks in place to ensure that only individuals 
        deemed responsible enough are allowed to successfully adopt children. This is to say that a 
        critical component of every adoption is acquiescence with applicable state laws and drafting out 
        a safe and secure adoption plan upon which every involved party can depend. These systems are 
        there to protect the best interests of any child facing adoption. However, the details and 
        complications involved can be a lot for the parties involved to deal with.Affordable Legal Help can 
        provide you with the needed legal assistance throughout the adoption process. 

    </p>

    <img src="/Image/Webp.net-resizeimage-2.png" class="bg3 img-fluid mt-4 mb-4" alt="child adoption image">
    
    <p class=" text-secondary  decor size15" >
        We are a family law firm with years of experience and qualified attorneys. With our professional 
        and unbundled legal service, we can save you lots of time, resources and effort, and finally help 
        you adopt the child of your dreams.  <br>
        By utilizing our unbundled legal services, we ensure that you get to take care of areas that do 
        not require the attention of an attorney. This is not to say we’ll leave you without guidance. 
        Our highly competent attorneys will duly handle every other important aspect of your case. All 
        you will be required to do is present yourself before the family court to prove your eligibility 
        for adopting a child.  <br>
        Affordable Legal Help will also handle details such as:

        <h4 class="text-dark pt-2 font-weight-normal mb-3 size25">Prospective Adoption Case Management</h4>
        <p class=" text-secondary  decor size15">With our team of adoption attorneys and social workers, we manage all the details and aspects of the adoption from the match until the baby is born and put up for adoption. </p>
        
        <h4 class="text-dark pt-2 font-weight-normal mb-3 size25">Dissolution of Parental Rights and Assignment of Children to Adoptive Parents</h4>
        <p class=" text-secondary  decor size15">In every state there are several ways in which a birth parent can put up their child for adoption with a potential adoptive parent. Each state and each method has different processes with varied rules for when a birth parent can give consent and when that consent becomes irreversible. As a leading family law firm, we specialize in drafting out and implementing a legal plan that affords our clients with the safest, most cost-effective and quickest plan for obtaining irreversible adoption consents.</p>

    </p>

    <h3 class="text-dark font-weight-normal mt-5 mb-4 size31" >Why choose our lawyers</h3>
    
    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Detailed explanation of the entire process.
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Guidance through the process of getting the needed adoption documents.
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Affordable and result-oriented.
    </p>

</section>


<section class="container-fluid bg-light paddings centre mt-5">

    <h2 class=" fontb text-center font-weight-bold size31 blue1" >Customers feedback</h2>
    <p  class="text-dark text-center texts font-weight-normal size14 mb-5 col-lg-8">
    Unbundling or A-La-Carte Services is gaining popularity among both attorneys and the public.
    </p>

    <div class="row container text-center mt-3">

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">

                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Affordable-Legal-Help-Testimonail-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>

                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">William Davis,Alaska</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"It’s already six months since I successfully adopted this beautiful baby. I have experienced only joy and a genuine sense of fulfillment ever since. Thanks to Affordable legal help  for making the entire process seamless."</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Ideal-Testimonail-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Lena Charles,Maryland</p>
                    <hr>
                    <p class="card-text text-black-50 size15">"There are very few family law firms out there that handle the adoption process professionally. This one is one of them. Thanks for changing my life by giving me a child."</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0  pt-4  flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/circle-cropped-1-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Carla Houston,Georgia</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"This experience with Affordable Legal Help Experts was great. They truly care about your needs. They know how to get you the proper help you need. They really helped put me at ease. Thank you so much for everything!"</p>
                </div>
            </div>
        </div>

    </div>

</section>




<?php include_once"footer.php"; ?>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script >
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<script async src="/client_validate.js?v=11"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php include "libs2.php"; ?>


</body>
</html>



