<?php
// require_once("maintenance.php");
// maintenance(TRUE);
?>
<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
$database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'childcustody' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title><?php echo $title; ?></title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<?php echo "<meta name='description' content='$meta_desc'>"?>

<!--yandex-->
<meta name="yandex-verification" content="0beccc11dc0dc9cb" />

<?php include "libs.php"; ?>

<style>

ul {
    margin-top: 0px;
    margin-bottom: 1rem;
    background-color: white;
}


li {
    border-bottom: 1px solid rgba(39, 40, 41, 0.2);
    padding: 20px;
}

li:hover {
    background-color:white;
}

.paddings{
    padding-top:90px; 
    padding-bottom:90px;
}

.pos-abs{
    position: absolute !important; 
    width:100%; 
}

.pos-inh{
    position: inherit !important;
}

.l-h{
    line-height: 0.9;
}

.connect-btn{
    padding: 22px !important;
}

.height11{
    height:300px;
}
</style>





<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>

</head>




<body id="fill">
    
<div class="sticky-top mb-1">
<div class="alert bg-info alert-dismissible  rounded-0 border-0 m-0 p-0">
    <button type="button" class="close text-white mt-0 pt-1" data-dismiss="alert">&times;</button>
    <p class="size14 text-white text-center pt-2 pb-2 pr-5 pl-2 mb-0">COVID-19 UPDATE: Law firms are still available to help. Set up a consultation from home today.</p>
</div>
</div>


<?php include_once "header.php"; ?>


<?php if(isset($_REQUEST['submitbtn']))
{
}?>

<section class="custody_bg bg2">
    <div class="container-fluid home_padding"><!--div 0 -->
    	<br />
        <h1 class="text-white  text-center jl_heading  font5">Find The Right Child Custody Lawyer In Your Zip Code</h1>
        
        <p class=" texts text-white text-center">Rectify your child adoption issues for as low as  750$-950$,Receive a free consultation immediately and payment plans are also availaible.</p>
        
        <?php 
        	if (isset($_POST['submitbtn'])){}
        ?>
        
        <br>
        <form class="ser_state888 mt-3 centre" method="post" ><!--form a -->
        
            <div class="col-9 pr-0 pl-0"><!--div a -->
            	
            	<div class="row">
                
                    <div class="col-12 col-lg-8 col-md-8 col-sm-12 pr-0 pl-0">
                        <input type="text" name="country" id="country" class="form-control font-weight-normal texts rounded-0 ser_box mt-2"  placeholder="Enter Your City Or Zipcode" autocomplete="off"/>
                        
                        <div class="pos-abs" >
                        <div id="countryList" class="texts text-dark font-weight-normal text-left bg-transparent l-h" >
                        
                        </div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-lg-4 col-md-4 col-sm-12 pl-0 pr-0 pos-inh">
                        <div  id="btnconnect"><!--div c -->
                            <input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn btn-danger btn-block connect-btn rounded-0 mt-2"/>
                        </div><!--div c -->
                    </div>

                    <?php
 if (isset($_POST['submitbtn'])){
    $_SESSION['city']=$_POST['country'];
    $i=$_SESSION['city'];
    
    $_SESSION['from_page']="Child custody";
    
    
    //$city1=$_POST['city'];
    $city_state = explode(",", $i);
    $query="SELECT * FROM `city` WHERE `City`='$city_state[0]' AND `State`='$city_state[1]' limit 1";
    $qu= $db->prepare($query);
    $qu->execute();
    $resultt=$qu->fetchAll(PDO::FETCH_OBJ);
    $row = $qu->fetch(PDO::FETCH_ASSOC);
    //$result=mysqli_query($conn,$query);
    //$check=mysqli_num_rows($result);
    
    // if($qu->rowCount() > 0){
    echo "<script type='text/javascript'> document.location = '/Complete-your-request'; </script>";	
    // }
    // else{
        
    //     echo "<script type='text/javascript'>$('#country').css({'border':'1px solid red'});</script>";
    //     echo "<span style='font-size:13px; color:#900;' class='error ml-5'>please enter valid US city</span>";
        
    // }
  }
?>
                    
                </div>
                
                
            </div><!--div a -->
                
                
                
                
        </form><!--form a -->
         
    </div><!--div 0 -->
    
</section>







<section class="container mt-5 pb-5">

    <h1 class="text-dark pt-4 font-weight-normal mb-3 size46" >Child Custody</h1>
    <p class=" text-secondary  decor size15" >
        After couples separate or divorce, what always – for couples with kids – follows is the problem of child 
        custody. In most parts of the world, including many parts of the USA, parents have physical custody and 
        legal custody rights to their children.  <br>
        The child custody process goes through stages such as complaints, parenting seminar, custody 
        conciliation, meditation, trial, and appeal, all of which are designed to ensure that the most 
        favorable settlement is reached.
    </p>

    <img src="/Image/Webp.net-resizeimage-800x567.png" class="bg3 img-fluid mt-4 mb-4" alt="divorce image">
    
    <p class=" text-secondary  decor size15" >
    Affordable legal help  provides realistic legal guidance or council based on the facts and circumstances 
    of your case. The law as it relates to your situation is explained in detail at your initial consultation. 
    If deemed fitting, we recommend co-parenting counseling and resources to assist in informing your 
    child/children about what is to come (separation or divorce). We explore available options to litigation
    with you, including arbitration, mediation and collaborative law. <br><br>
    We offer unbundled child custody services that are affordable, and are aimed at encouraging you to 
    seek legal council and representation. Our team of experienced lawyers work tirelessly to get results 
    that fulfill the interests of clients. 



        <h4 class="text-dark pt-4 font-weight-normal mb-4 size25">Legal Custody and Physical Custody</h4>
        
        <p class=" text-secondary  decor size15"><span class="size20 font-weight-bold">Physical custody:</span> This is the right to have actual physical custody of your child. This right is almost always shared by parents, although shared here doesn’t necessarily mean 50/50. Shared custody schedules are varied and usually depend on the peculiarity of a child custody case. The lawyers at Affordable Legal Help are more than qualified to work with you to arrive at a schedule that works best for you and your child.  </p>
        <p class=" text-secondary  decor size15"><span class="size20 font-weight-bold">Legal custody:</span> The right to make decisions concerning the welfare and health of your child. Like physical custody, this right is usually shared by parents. Legal custody gives parents access to medical and school records and stipulates that each stay up to date on important child related decisions or matters. </p>
        <p class=" text-secondary  decor size15">In most parts of the world, custody agreements and orders are subject to modification at any time to suit the child’s best interests. Until a child reaches the age of eighteen, he or she remains subject to an order. </p>

    </p>

    <h3 class="text-dark font-weight-normal mt-5 mb-4 size31" >Why choose our lawyers</h3>
    
    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Our lawyers Prioritizes your child’s best interests.
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Our Lawyers Will guarantee that child support is secured. 
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Experienced and expertly presented negotiations to give you the best outcome. 
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Highly affordable. 
    </p>

</section>


<section class="container-fluid bg-light paddings centre mt-5">

    <h2 class=" fontb text-center font-weight-bold size31 blue1" >Customers feedback</h2>
    <p  class="text-dark text-center texts font-weight-normal size14 mb-5 col-lg-8">
    Unbundling or A-La-Carte Services is gaining popularity among both attorneys and the public.
    </p>

    <div class="row container text-center mt-3">

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">

                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Testimonial-Image-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>

                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Michael Smith,Hawaii</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"Wow! I can’t believe it. I won the child custody case. I would love to use this opportunity to say thanks to the team of professional attorneys at Affordable Legal Help. I never imagined that it was possible to get top-rated legal services at affordable rates. Once again, thanks!"</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Women-Testimonail-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Gina Teague, Arizona</p>
                    <hr>
                    <p class="card-text text-black-50 size15">"One of the best decisions I have made in my life is hiring Affordable Legal Help to handle my child custody case. I have never seen lawyers work with so much compassion, dedication and professionalism. You guys are the best!"</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0  pt-4  flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/IMG-Patient-5-119x119.jpg" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">David Pledra,New York</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"I have been a client of Affordable legal Help for some time. I found this Family law firm to be most professional and efficient. I would highly recommend them to my family, friends or anyone seeking legal services."</p>
                </div>
            </div>
        </div>

    </div>

</section>





<?php include_once"footer.php"; ?>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script >
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<script async src="/client_validate.js?v=11"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php include "libs2.php"; ?>


</body>
</html>



