<?php
// require_once("maintenance.php");
// maintenance(TRUE);
?>
<?php 
include_once "config/database.php"; 
 $database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'contactus' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <title><?php echo $title; ?></title>
    
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />    
        
    <?php echo "<meta name='description' content='$meta_desc'>"?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<!--Libraries file-->
<?php include "libs.php"; ?>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "CONTACT US",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>
</head>

<body class=" bg-white">

<?php include_once "header.php"; ?>
<?php 
$database=new Database();

$db = $database->getConnection();
            
if (isset($_POST['submitbtn']))
{
    $Name=$_POST['fname'];
    $Email=$_POST['email'];
    $Phone=$_POST['mob'];
    $Subject=$_POST['lname'];
    $Message=$_POST['msg'];
     //write query
     $query = "INSERT INTO
            contact_us
    SET
        Name=:Name, Email=:Email, Phone=:Phone, Subject=:Subject, Message=:Message";

    $stmt = $db->prepare($query);

    // posted values
    $Name=htmlspecialchars(strip_tags($Name));
    $Email=htmlspecialchars(strip_tags($Email));
    $Phone=htmlspecialchars(strip_tags($Phone));
    $Subject=htmlspecialchars(strip_tags($Subject));
    $Message=htmlspecialchars(strip_tags($Message));
    // bind values 
    $stmt->bindParam(":Name", $Name);
    $stmt->bindParam(":Email", $Email);
    $stmt->bindParam(":Phone", $Phone);
    $stmt->bindParam(":Subject", $Subject);
    $stmt->bindParam(":Message", $Message);
    if($stmt->execute()){
        // echo "succes";
        
          }else{

    }
}
    
    ?>

<div class="jumbotron jumbotron-fluid bg1 contact_bg border-0">
    <div class="paddings">
        <h1 class="size46 text-white text-center ">CONTACT US</h1>
    </div>
</div>



<section class="container-fluid text-left text-dark mt-5">
    <div class="row">
    	
        <div class="col-lg-6 col-md-6 col-sm-12 col-12 d-block">
        	<h2 class="text-white font-weight-normal mb-1 pb-2 pt-2 pl-2 bg-secondary font2 xl_heading"> CONTACT US</h2>
            <form class="contact-form1" method="post" >
                <div class="form-group mb-1">
                    <input type="text" class="form-control p-4 m-0" name="fname" id="fname"  placeholder="Full Name" style="border-radius:0px;"/> 
                </div>
                
                <div class="form-group mb-1">
                    <input type="text" class="form-control p-4 m-0" name="email" id="email" placeholder="Email Address" style="border-radius:0px;"/>
                </div>
                
                <div class="form-group mb-1">
                    <input type="tel" class="form-control p-4 m-0" name="mob" id="mob" placeholder="Phone No" style="border-radius:0px;"/>
                </div>
                
                <div class="form-group mb-1">
                    <input type="text" class="form-control p-4 m-0" name="lname" id="lname" placeholder="subject" style="border-radius:0px;"/>
                </div>
                <div class="form-group mb-1">
                    
                    <textarea class="form-control p-4" name="msg" id="msg" placeholder="Message" rows="8" cols="60" style="border-radius:0px;"></textarea>
            </div>
                <div class="form-group">
                    <center>
                    <input type="button" class="btn btn-lg btn-danger btn-block font-weight-normal m-auto" value="Submit"  data-target="#modal1" data-toggle="modal" style="border-radius:0px"/>
                     <div class="modal fade" id="modal1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header bg-secondary">
                                    <h3 class="text-white font-weight-normal font2 m-auto xl_heading">Thank You<br /> For Contacting Us</h3>
                                </div>
                                
                                <div class="modal-body">
                                    <div class="container ">
                                        <h6 class="text-dark pt-4 pb-4 font-weight-normal font2 heading">One of our representatives will be in contact with you shortly regarding your inquiry. If you ever have any questions that require immediate assistance, please call us at<br /> <b>844 944 5342</b></h6>                      
                                    </div>
                                </div>
                                
                                <div class="modal-footer p-0 bg-light">
                                    <input type="submit" name="submitbtn" class="btn btn-lg btn-danger font-weight-normal btn-block m-auto" value="Close"  style="border-radius:0px"/>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    </center>
                </div>
                <br />
            
            </form>
        </div>
        
        <div class="child_block col-lg-5 col-md-6 col-sm-12 col-12 d-block m-auto text-left">
        <div class="contactUs_bg1">
            <div class="d-block text-white m-auto xl_heading"><i class="fas fa-info-circle"> Contact Info</i></div>
            <hr style="background-color:cadetblue;"/>
            <dl>
                <dt class="texts text-white font-weight-bold"><i class="fa fa-envelope mr-4"></i>Email:</dt>
                <dd><a class="text-success xs_texts font-weight-normal" style="margin-left:44px;" href="mailto:info@affordablelegalhelp.com">info@affordablelegalhelp.com</a></dd>
            </dl>
            <dl>
                <dt class="texts text-white font-weight-bold"><i class="fa fa-phone mr-4"></i> Phone:</dt>
                <dd><a class="text-success xs_texts font-weight-normal" style="margin-left:45px;"  href="tel:844 944 5342">844 944 5342</a></dd>
            </dl>
        </div>
        </div>
        
    </div>
</section>

<?php include_once "footer.php"; ?>

<?php include_once "libs2.php"; ?>

<script async src="client_validate.js?v=10"></script>





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>

</body>
</html>