<?php
// require_once("maintenance.php");
// maintenance(TRUE);
?>
<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
$database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'divorce' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title>Divorce | Find Affordable Legal Help with us </title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<?php echo "<meta name='description' content='$meta_desc'>"?>

<!--yandex-->
<meta name="yandex-verification" content="0beccc11dc0dc9cb" />

<?php include "libs.php"; ?>

<style>

ul {
    margin-top: 0px;
    margin-bottom: 1rem;
    background-color: white;
}


li {
    border-bottom: 1px solid rgba(39, 40, 41, 0.2);
    padding: 20px;
}

li:hover {
    background-color:white;
}

.paddings{
    padding-top:90px; 
    padding-bottom:90px;
}

.pos-abs{
    position: absolute !important; 
    width:100%; 
}

.pos-inh{
    position: inherit !important;
}

.l-h{
    line-height: 0.9;
}

.connect-btn{
    padding: 22px !important;
}

.height11{
    height:300px;
}
</style>





<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>

</head>




<body id="fill">
    
<div class="sticky-top mb-1">
<div class="alert bg-info alert-dismissible  rounded-0 border-0 m-0 p-0">
    <button type="button" class="close text-white mt-0 pt-1" data-dismiss="alert">&times;</button>
    <p class="size14 text-white text-center pt-2 pb-2 pr-5 pl-2 mb-0">COVID-19 UPDATE: Law firms are still available to help. Set up a consultation from home today.</p>
</div>
</div>


<?php include_once "header.php"; ?>


<?php if(isset($_REQUEST['submitbtn']))
{
}?>

<section class="divorce_bg bg2">
    <div class="container-fluid home_padding"><!--div 0 -->
    	<br />
        <h1 class="text-white  text-center jl_heading  font5">Find The Right Divorce Lawyer In Your zip Code</h1>
        
        <p class=" texts text-white text-center">Rectify your contested and uncontested divorce issues for as low as  1250$ to 1500$,Receive a free consultation Immediately! and payment plans are also availaible.</p>
        
        <?php 
        	if (isset($_POST['submitbtn'])){}
        ?>
        
        <br>
        <form class="ser_state888 mt-3 centre" method="post" ><!--form a -->
        
            <div class="col-9 pr-0 pl-0"><!--div a -->
            	
            	<div class="row">
                
                    <div class="col-12 col-lg-8 col-md-8 col-sm-12 pr-0 pl-0">
                        <input type="text" name="country" id="country" class="form-control font-weight-normal texts rounded-0 ser_box mt-2"  placeholder="Enter Your City Or Zipcode" autocomplete="off"/>
                        
                        <div class="pos-abs" >
                        <div id="countryList" class="texts text-dark font-weight-normal text-left bg-transparent l-h" >
                        
                        </div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-lg-4 col-md-4 col-sm-12 pl-0 pr-0 pos-inh">
                        <div  id="btnconnect"><!--div c -->
                            <input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn btn-danger btn-block connect-btn rounded-0 mt-2"/>
                        </div><!--div c -->
                    </div>

                    <?php
 if (isset($_POST['submitbtn'])){
    $_SESSION['city']=$_POST['country'];
    $i=$_SESSION['city'];
    
    $_SESSION['from_page']="Divorce";
    
    
    //$city1=$_POST['city'];
    $city_state = explode(",", $i);
    $query="SELECT * FROM `city` WHERE `City`='$city_state[0]' AND `State`='$city_state[1]' limit 1";
    $qu= $db->prepare($query);
    $qu->execute();
    $resultt=$qu->fetchAll(PDO::FETCH_OBJ);
    $row = $qu->fetch(PDO::FETCH_ASSOC);
    //$result=mysqli_query($conn,$query);
    //$check=mysqli_num_rows($result);
    
    // if($qu->rowCount() > 0){
    echo "<script type='text/javascript'> document.location = '/Complete-your-request'; </script>";	
    // }
    // else{
        
    //     echo "<script type='text/javascript'>$('#country').css({'border':'1px solid red'});</script>";
    //     echo "<span style='font-size:13px; color:#900;' class='error ml-5'>please enter valid US city</span>";
        
    // }
  }
?>
                    
                </div>
                
                
            </div><!--div a -->
                
                
                
                
        </form><!--form a -->
         
    </div><!--div 0 -->
    
</section>







<section class="container mt-5 pb-5">

    <h1 class="text-dark pt-4 font-weight-normal mb-3 size46" >Divorce</h1>
    <p class=" text-secondary  decor size15" >
        Divorce can be one of the most difficult and strenuous experience of your life. Your divorce can 
        include spousal maintenance, division of community property, asset protection, and child support 
        and child custody. Processing all the details in the aforementioned areas can leave you overwhelmed 
        and in a lot of stress. For this reason, the best and most effective approach to take is to hire a 
        qualified divorce attorney or family legal help firm to handle proceedings.

    </p>

    <img src="/Image/Affordable-Divorce-Help-800x667-1.jpg" class="bg3 img-fluid mt-4 mb-4" alt="divorce image">
    
    <p class=" text-secondary  decor size15" >
        At Affordable Legal Help, our highly capable team of professionals work to ensure that you get the 
        treatment and attention that your special case deserves from the moment you visit our firm to seek 
        consultation and representation. We help you get a full grasp of the technicalities involved and make 
        the entire process easier for you  <br><br>
        By offering unbundled legal services, we help you through the entire divorce process in a manner that 
        ensures that all sorts of complications are avoided, especially those involving finance. In reality, 
        it is not always that unbundled legal services manage to deliver desired results. There are times
        when divorce cases are complicated and require the attention of top professionals. Nevertheless, 
        this is usually not the case; hence, our unbundled services, offered at affordable rates, will more 
        than likely get the job done. 
    </p>

    <h3 class="text-dark font-weight-normal mt-5 mb-4 size31" >Why choose our divorce lawyers</h3>
    
    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        With our divorce attorneys handling affairs, couples looking for contested or uncontested divorce are able to reach important agreements faster. 
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        This service affords you a mediator to handle affairs between you and your spouse throughout the entire divorce process. It is common for couples going through divorce to hold grudges and pent up anger, both of which can lead to more fights and further fan the flames of unnecessary legal complications. You can avoid all of these by hiring us. 
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        A divorce can be an emotionally draining experience for most people. By hiring the trustworthy divorce attorneys at Affordable Legal Help, you are able to lessen the emotional stress that comes with going through a divorce settlement.   
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Guaranteed protection of your rights by our seasoned divorce attorneys in all over the United States. This is possible because we are a family legal service with an in depth understanding of the divorce process. Your best interests will always be in consideration. 
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        You’ll always get a shoulder to lean on. For us, it more than giving you the best representation and legal council, we go a step further by showing care.
    </p>

</section>


<section class="container-fluid bg-light paddings centre mt-5">

    <h2 class=" fontb text-center font-weight-bold size31 blue1" >Customers feedback</h2>
    <p  class="text-dark text-center texts font-weight-normal size14 mb-5 col-lg-8">
    Unbundling or A-La-Carte Services is gaining popularity among both attorneys and the public.
    </p>

    <div class="row container text-center mt-3">

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">

                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/success-story-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>

                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Sean Walker,Florida</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"Had a wonderful experience from working with this firm. There is hardly any law firm out there that handles divorce cases as professionally as this one. Highly recommended!"</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Success-Stories-1-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Emy Claura, Ohio</p>
                    <hr>
                    <p class="card-text text-black-50 size15">"I can’t feel grateful enough, really. At a point, it felt like my world was falling apart with the whole divorce thing. Didn’t think I’d manage to pull through. You know what? Not only did I pull through, I did so without hassles and complications. This is surely one of the best family legal services around. "</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0  pt-4  flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Client-testiminial-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Mike Wilson,Georgia</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"This experience with Affordable Legal Help Experts was great. They truly care about your needs. They know how to get you the proper help you need. They really helped put me at ease. Thank you so much for everything!!!!"</p>
                </div>
            </div>
        </div>

    </div>

</section>




<?php include_once"footer.php"; ?>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script >
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<script async src="/client_validate.js?v=11"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php include "libs2.php"; ?>


</body>
</html>



