<?php
// require_once("maintenance.php");
// maintenance(TRUE);
?>
<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
$database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'faq' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title><?php echo $title; ?> </title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<?php echo "<meta name='description' content='$meta_desc'>"?>
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">
<!--#Libraries file#-->
<script defer src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<?php include "libs.php"; ?>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>
</head>



<body>
    
<?php include_once "header.php"; ?>


<div class="jumbotron jumbotron-fluid bg1 faq_bg border-0">
    <div class="paddings">
        <h1 class="size46 text-white text-center ">Frequently Ask Questions</h1>
    </div>
</div>

<div class="container mb-5 mt-5">

    <div class="row">

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>


    </div>
</div>





<?php include_once"footer.php"; ?>



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>

</body>
</html>

