<?php
// require_once("maintenance.php");
// maintenance(TRUE);
?>
<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
$database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'parents' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title><?php echo $title; ?></title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<?php echo "<meta name='description' content='$meta_desc'>"?>

<!--yandex-->
<meta name="yandex-verification" content="0beccc11dc0dc9cb" />

<?php include "libs.php"; ?>

<style>

ul {
    margin-top: 0px;
    margin-bottom: 1rem;
    background-color: white;
}


li {
    border-bottom: 1px solid rgba(39, 40, 41, 0.2);
    padding: 20px;
}

li:hover {
    background-color:white;
}

.paddings{
    padding-top:90px; 
    padding-bottom:90px;
}

.pos-abs{
    position: absolute !important; 
    width:100%; 
}

.pos-inh{
    position: inherit !important;
}

.l-h{
    line-height: 0.9;
}

.connect-btn{
    padding: 22px !important;
}

.height11{
    height:300px;
}
</style>





<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>

</head>




<body id="fill">
    
<div class="sticky-top mb-1">
<div class="alert bg-info alert-dismissible  rounded-0 border-0 m-0 p-0">
    <button type="button" class="close text-white mt-0 pt-1" data-dismiss="alert">&times;</button>
    <p class="size14 text-white text-center pt-2 pb-2 pr-5 pl-2 mb-0">COVID-19 UPDATE: Law firms are still available to help. Set up a consultation from home today.</p>
</div>
</div>


<?php include_once "header.php"; ?>


<?php if(isset($_REQUEST['submitbtn']))
{
}?>

<section class="grand_parent_bg bg2">
    <div class="container-fluid home_padding"><!--div 0 -->
    	<br />
        <h1 class="text-white  text-center jl_heading  font5">Find the Right Grandparents Rights Lawyer In Your Zip Code</h1>
        
        <p class=" texts text-white text-center">Rectify your Grandparents right issues for as low as 750$-950$, Receive a free consultation Immediately,And payment palns are also availaible.</p>
        
        <?php 
        	if (isset($_POST['submitbtn'])){}
        ?>
        
        <br>
        <form class="ser_state888 mt-3 centre" method="post" ><!--form a -->
        
            <div class="col-9 pr-0 pl-0"><!--div a -->
            	
            	<div class="row">
                
                    <div class="col-12 col-lg-8 col-md-8 col-sm-12 pr-0 pl-0">
                        <input type="text" name="country" id="country" class="form-control font-weight-normal texts rounded-0 ser_box mt-2"  placeholder="Enter Your City Or Zipcode" autocomplete="off"/>
                        
                        <div class="pos-abs" >
                        <div id="countryList" class="texts text-dark font-weight-normal text-left bg-transparent l-h" >
                        
                        </div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-lg-4 col-md-4 col-sm-12 pl-0 pr-0 pos-inh">
                        <div  id="btnconnect"><!--div c -->
                            <input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn btn-danger btn-block connect-btn rounded-0 mt-2"/>
                        </div><!--div c -->
                    </div>

                    <?php
 if (isset($_POST['submitbtn'])){
    $_SESSION['city']=$_POST['country'];
    $i=$_SESSION['city'];
    
    $_SESSION['from_page']="Grand Parent Rights";
    
    
    
    //$city1=$_POST['city'];
    $city_state = explode(",", $i);
    $query="SELECT * FROM `city` WHERE `City`='$city_state[0]' AND `State`='$city_state[1]' limit 1";
    $qu= $db->prepare($query);
    $qu->execute();
    $resultt=$qu->fetchAll(PDO::FETCH_OBJ);
    $row = $qu->fetch(PDO::FETCH_ASSOC);
    //$result=mysqli_query($conn,$query);
    //$check=mysqli_num_rows($result);
    
    // if($qu->rowCount() > 0){
    echo "<script type='text/javascript'> document.location = '/Complete-your-request'; </script>";	
    // }
    // else{
        
    //     echo "<script type='text/javascript'>$('#country').css({'border':'1px solid red'});</script>";
    //     echo "<span style='font-size:13px; color:#900;' class='error ml-5'>please enter valid US city</span>";
        
    // }
  }
?>
                    
                </div>
                
                
            </div><!--div a -->
                
                
                
                
        </form><!--form a -->
         
    </div><!--div 0 -->
    
</section>







<section class="container mt-5 pb-5">

    <h1 class="text-dark pt-4 font-weight-normal mb-3 size46" >Grand Parents Rights</h1>
    <p class=" text-secondary  decor size15" >
        The kind of relationship that grandparents share with their grandchildren is special; one that 
        most grandchildren live to remember for the entirety of their lives. Grandparents are exceedingly 
        proud of their grandchildren, and spending quality time with them is often a source of joy and 
        profound happiness. On a rather sad note, divorce can come between the special relationship shared 
        by grandparents and their grandchildren, resulting to moments of tension and grief.

    </p>

    <img src="/Image/Grandparents-Rights-800x667-1.jpg" class="bg3 img-fluid mt-4 mb-4" alt="divorce image">
    
    <p class=" text-secondary  decor size15" >
        Grandparents to children whose parents have separated or are on the verge of separation usually 
        experience difficulties with coping during such sad times. The thought of your grandchild being 
        raised by the other parent and their new spouse can be unnerving, especially in the face of the 
        real possibility of not being able to share happy moments as often as before. Events like this 
        can negatively impact the relationship between involved families. If you are intent on preventing 
        matters from going down the path of deterioration, it is important to do what you can to at least 
        gain visitation rights as a grandparent.   <br><br>
        As a matter of fact, in a times like this, the best course of action to take as a grandparent is 
        to seek professional legal council and representation. You’ll need to work with a family law firm 
        with an exceptionally brilliant track record.  <br><br>
        Acknowledging this need, we at Affordable legal Help are committed to providing you with both professional 
        and unbundled legal services at enticing rates.  <br><br>
        At Affordable Legal Help, we understand the dilemmas that most grandparents go through when their children 
        part ways. Our brilliant and experienced attorneys are passionate about assisting grandparents in 
        claiming their legal rights, including child custody, guardianship, child visitation 
        and more.
    </p>

    <p class="text-secondary font-weight-bold pt-4 decor size15">
    We frequently handle grandparents' rights in cases involving:
    </p>

    <p class="text-secondary decor size15">
        	Divorce or separation of grandchild's parents
    </p>

    <p class="text-secondary decor size15">
        	Deceased parent of grandchild
    </p>

    <p class="text-secondary decor size15">
        	Grandchild living with grandparent(s)
    </p>





    <h3 class="text-dark font-weight-normal mt-5 mb-4 size31" >Why choose our lawyers</h3>
    
    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Meticulous filing of all necessary documents.
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Significantly lessens the stress that comes with divorce.
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Affordable and result-oriented.
    </p>

    <p class="text-secondary decor size15">
        <span><i class="fa fa-check fa-1x pr-2 pt-1 text-dark " aria-hidden="true"></i></span>
        Prioritizes the child’s best interests.
    </p>

</section>


<section class="container-fluid bg-light paddings centre mt-5">

    <h2 class=" fontb text-center font-weight-bold size31 blue1" >Customers feedback</h2>
    <p  class="text-dark text-center texts font-weight-normal size14 mb-5 col-lg-8">
    Unbundling or A-La-Carte Services is gaining popularity among both attorneys and the public.
    </p>

    <div class="row container text-center mt-3">

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">

                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/minified-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>

                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Todd Asher,Ohio</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"Considering my old age, I didn’t think I would be able to get through the stress brought upon me by the separation of my grandchild’s parents. Even worse, I feared I might never get the opportunity to spend quality time with my beautiful granddaughter again. What can I say? I thought wrong. Thanks to this wonderful law firm for playing a huge role in making me smile again. "</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0 pt-4 flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Affordable-legal-Help-Testimonial-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Sharon Huth,Michigan</p>
                    <hr>
                    <p class="card-text text-black-50 size15">"Feels like a dream, but it’s actually not. This is real. I have been given custody of my grandchild. I am so grateful and happy. Thank you!  If you are reading this, this is the law firm to work with. The care, professionalism and results… words fail me. "</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4 p-4 col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card  rounded-0  pt-4  flex-fill story-hov">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5 img_section2">
                    <img src="/Image/Grand-parents-Rights-120x120.png" class="img-fluid border-0 rounded-circle"  alt="Responsive image">
                </div>
                <div class="card-body">
                    <p class="card-title font-weight-normal blue1 texts">Ridge Walder,Washington DC</p>
                    <hr>
                    <p class="card-text text-black-50 size15" >"My experience with "Affordable Legal Help" was very professional from start to finish. I didn’t experience a long waiting time and the staff was very knowledgeable and expressed concerned that all my needs we’re being met. I would strongly recommend them to anyone because of the heart they have for their clients and the trained staff"</p>
                </div>
            </div>
        </div>

    </div>

</section>



<?php include_once"footer.php"; ?>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script >
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<script async src="/client_validate.js?v=11"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php include "libs2.php"; ?>


</body>
</html>



