<?php
// require_once("maintenance.php");
// maintenance(TRUE);
include_once "config/database.php"; 
include_once "object/login.php";
$database=new Database();
 $db = $database->getConnection();
$title="";
$meta_desc="";


// $data = "SELECT * FROM `meta_data` WHERE page_name like 'home'";
// $run = mysqli_query($con,$data);
// while($row=mysqli_fetch_array($run)){
//     $title = $row['title']; 
//     $meta_desc = $row['meta_desc'];
// } 
$sqq ="SELECT * FROM meta_data WHERE page_name = 'privacy' ";
                
                $quey= $db->prepare($sqq);

                // // posted values
              
                // $query->bindParam(":id", $this->state);
                // $query->bindParam(":Catogory", $this->Catogory);
                $quey->execute();
                $resu=$quey->fetchAll(PDO::FETCH_OBJ);
                $row = $quey->fetch(PDO::FETCH_ASSOC);
                if($quey->rowCount() > 0)
                {
                    foreach($resu as $resul){
                       $title =htmlentities($resul->title);
                       $meta_desc = htmlentities($resul->meta_desc);
                       
                    }
                }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $title ?></title>

<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
   
    <?php echo "<meta name='description' content='$meta_desc'>"?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<!--#Libraries file#-->
<?php include "libs.php"; ?>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Privacy Policy",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Your Privacy"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "How We Use Your Information"
} ]
</script>

</head>
<body class="bg-light fontb">
    
<?php include_once "header.php";?>
	
<section class=" mt-5 mb-5 ml-1 mr-1">
    <div class="container text-left bottom_padding  bg-white">
    
        <h1 class="header_font1 text-center pt-3 home_heading_settings size46">Privacy Policy</h1><hr /><br />
        
        <div class="container mb-5">
            <p class="text-secondary font-weight-normal size16 decor">Our Privacy Policy was last updated and posted on December 5, 2019. It governs the privacy terms of our Website, located at <a href="https://affordablelegalhelp.com">https://affordablelegalhelp.com</a>, sub-domains, and any associated web-based and mobile applications (collectively, "Website"), as owned and operated by Affordable Legal Help. Any capitalized terms not defined in our Privacy Policy, have the meaning as specified in our Terms of Service.<br /><br />
Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. We use your Personal Information only for providing and improving the website. By using the website, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible at https://affordablelegalhelp.com. The following outlines our privacy policy.
            </p>
        </div>
        
        <div class="container mb-5">
            <ul class="text-secondary font-weight-normal size15 decor  pl-2">
                <li>
                Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
                </li><br />
                <li>
                We will collect and use personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.
                </li><br />
                <li>
                We will only retain personal information as long as necessary for the fulfillment of those purposes.
                </li><br />
                <li>
                Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.
                </li><br />
                <li>
                We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
                </li><br />
                <li>
                We will make readily available to customers information about our policies and practices relating to the management of personal information.
                </li>
            </ul>
        </div>
        
        <div class="container mb-5 mt-5">
            <h3 class="text-dark font-weight-bold heading">Your Privacy</h3>
            <p class="text-secondary font-weight-normal size15 decor">Affordable Legal Help follows all legal requirements to protect your privacy. Our Privacy Policy is a legal statement that explains how we may collect information from you, how we may share your information, and how you can limit our sharing of your information. We utilize the Personal Data you offer in a way that is consistent with this Personal privacy Policy. If you provide Personal Data for a particular reason, we could make use of the Personal Data in connection with the reason for which it was provided. For example, registration info sent when developing your account, might be used to suggest products to you based on past acquisitions. We might use your Personal Data to offer access to services on the Website and monitor your use of such services. Affordable Legal Help may also utilize your Personal Data and various other personally non-identifiable info gathered through the Website to assist us with improving the material and functionality of the Website, to much better comprehend our users, and to improve our services. You will see terms in our Privacy Policy that are capitalized. These terms have meanings as described in the Definitions section below.
            </p>
        </div>
        
        
        <div class="container mb-5 mt-5">
            <p class="text-dark font-weight-bold heading">Definitions</p>
            <p class="text-secondary font-weight-normal size15 decor">"Non Personal Information" is information that is not personally identifiable to you and that we automatically collect when you access our Website with a web browser. It may also include publicly available information that is shared between you and others.
"Personally Identifiable Information" is non-public information that is personally identifiable to you and obtained in order for us to provide you our Website. Personally Identifiable Information may include information such as your name, email address, and other related information that you provide to us or that we obtain about you.

            </p>
        </div>
        
        <div class="container mb-5 mt-5">
            <p class="text-dark font-weight-bold heading">Information We Collect</p>
            <p class="text-secondary font-weight-normal size15 decor">Generally, you control the amount and type of information you provide to us when using our Website.
As a Visitor, you can browse our website to find out more about our Website. You are not required to provide us with any Personally Identifiable Information as a Visitor.

            </p>
        </div>
        
        <div class="container mb-4 mt-5">
            <p class="text-dark font-weight-bold heading">Computer Information Collected</p>
            <p class="text-secondary font-weight-normal size15 decor">When you use our Website, we automatically collect certain computer information by the interaction of your mobile phone or web browser with our Website. Such information is typically considered Non Personal Information. We also collect the following:</p>
            
        </div>
        
        <div class="container mb-5">
                <ul class="text-secondary font-weight-normal size15 decor mt-2 pl-2">
                    <li>
                    <b class="font-weight-bold">Cookies</b><br>
                    Our Website uses "Cookies" to identify the areas of our Website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our Website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our Website correctly or at all. We never place Personally Identifiable Information in Cookies.
                    </li><br />
                    <li>
                    <b class="font-weight-bold">Geographical Information</b><br>
                    When you use the mobile application, we may use GPS technology (or other similar technology) to determine your current location in order to determine the city you are located in and display information with relevant data or advertisements. We will not share your current location with other users or partners. If you do not want us to use your location for the purposes set forth above, you should turn off the location services for the mobile application located in your account settings or in your mobile phone settings and/or within the mobile application.
                    </li><br />
                    <li>
                    <b class="font-weight-bold">Automatic Information</b><br>
                    We automatically receive information from your web browser or mobile device. This information includes the name of the website from which you entered our Website, if any, as well as the name of the website to which you're headed when you leave our website. This information also includes the IP address of your computer/proxy server that you use to access the Internet, your Internet Website provider name, web browser type, type of mobile device, and computer operating system. We use all of this information to analyze trends among our Users to help improve our Website. 
                    </li><br />
                    <li>
                    <b class="font-weight-bold">Log Data</b><br>
                    Like many Website operators, we collect information that your browser sends whenever you visit our Website ("Log Data"). This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Website that you visit, the time and date of your visit, the time spent on those pages and other statistics.
                    </li><br />
                    
                </ul>
                
                <p class="text-secondary font-weight-normal size15 decor"> Under the Child's Online Privacy Security Act, no Website operator can require, as a condition to involvement in an activity, that a child younger than 13 years of age divulge more details than is reasonably required. Affordable Legal Help abides by this demand. Affordable Legal Help just collects information willingly offered; no information is gathered passively. children under 13 can submit only their email address when sending us an email in our "Contact Us" area. Affordable Legal Help makes use of the email address to respond to a one-time demand from a child under 13 and afterwards deletes the email address. In case Affordable Legal Help collects and maintains personal information relating to a child under 13, the parent may send out an email to us to review, alter and/or erase such info as well as to decline to enable any additional collection or use of the child's information.</p>
               
            
        </div>
        
        <div class="container mb-3 mt-5">
            <p class="text-dark font-weight-bold heading">How We Use Your Information</p>
            <p class="text-secondary font-weight-normal size15 decor">We use the information we receive from you as follows:
                
            </p>
        </div>
        
        <div class="container mb-5 mt-5">
                <ul class="text-secondary font-weight-normal size15 decor pl-2">
                    <li>
                    <b class="font-weight-bold">Customizing Our Website</b><br>
                    We may use the Personally Identifiable information you provide to us along with any computer information we receive to customize our Website.
                    </li><br />
                    <li>
                    <b class="font-weight-bold">Sharing Information with Affiliates and Other Third Parties</b><br>
                    We do not sell, rent, or otherwise provide your Personally Identifiable Information to third parties for marketing purposes. We may provide your Personally Identifiable Information to affiliates that provide services to us with regards to our Website (i.e. payment processors, Website hosting companies, etc.); such affiliates will only receive information necessary to provide the respective services and will be bound by confidentiality agreements limiting the use of such information.
                    
                    </li><br />
                    <li>
                    <b class="font-weight-bold">Data Aggregation</b><br>
                    We retain the right to collect and use any Non Personal Information collected from your use of our Website and aggregate such data for internal analytics that improve our Website and Service as well as for use or resale to others. At no time is your Personally Identifiable Information included in such data aggregations.
                    </li><br />
                    <li>
                    <b class="font-weight-bold">Legally Required Releases of Information</b><br>
                    We may be legally required to disclose your Personally Identifiable Information, if such disclosure is (a) required by subpoena, law, or other legal process; (b) necessary to assist law enforcement officials or government enforcement agencies; (c) necessary to investigate violations of or otherwise enforce our Legal Terms; (d) necessary to protect us from legal action or claims from third parties including you and/or other Members; and/or (e) necessary to protect the legal rights, personal/real property, or personal safety of Affordable Legal Help, our Users, employees, and affiliates.
                    </li>
                    
                </ul>
            </h5>
        </div>
        
        <div class="container mb-5 mt-5">
            <p class="text-dark font-weight-bold heading">Opt-Out</p>
            <p class="text-secondary font-weight-normal size15 decor">We offer you the chance to "opt-out" from having your personally identifiable information used for particular functions, when we ask you for this detail. When you register for the website, if you do not want to receive any additional material or notifications from us, you can show your preference on our registration form.
            </p>
        </div>
        
        <div class="container mb-5 mt-5">
            <p class="text-dark font-weight-bold heading">Links to Other Websites</p>
            <p class="text-secondary font-weight-normal size15 decor">Our Website may contain links to other websites that are not under our direct control. These websites may have their own policies regarding privacy. We have no control of or responsibility for linked websites and provide these links solely for the convenience and information of our visitors. You access such linked Websites at your own risk. These websites are not subject to this Privacy Policy. You should check the privacy policies, if any, of those individual websites to see how the operators of those third-party websites will utilize your personal information. In addition, these websites may contain a link to Websites of our affiliates. The websites of our affiliates are not subject to this Privacy Policy, and you should check their individual privacy policies to see how the operators of such websites will utilize your personal information.
            </p>
        </div>
        
        <div class="container mb-5 mt-5">
            <p class="text-dark font-weight-bold heading">Security</p>
            <p class="text-secondary font-weight-normal size15 decor">The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security. We utilize practical protection measures to safeguard against the loss, abuse, and modification of the individual Data under our control. Personal Data is kept in a secured database and always sent out by means of an encrypted SSL method when supported by your web browser. No Web or email transmission is ever totally protected or mistake cost-free. For example, email sent out to or from the Website may not be protected. You must take unique care in deciding what info you send to us by means of email.
            </p>
        </div>
        
        <div class="container mb-5 mt-5">
            <h3 class="text-dark font-weight-bold heading">Privacy Policy Updates</h3>
            <p class="text-secondary font-weight-normal size15 decor">We reserve the right to modify this Privacy Policy at any time. You should review this Privacy Policy frequently. If we make material changes to this policy, we may notify you on our Website, by a blog post, by email, or by any method we determine. The method we chose is at our sole discretion. We will also change the "Last Updated" date at the beginning of this Privacy Policy. Any changes we make to our Privacy Policy are effective as of this Last Updated date and replace any prior Privacy Policies.
            </p>
        </div>
        
        <div class="container mb-5 mt-5 pb-5">
            <h3 class="text-dark font-weight-bold heading">Questions About Our Privacy Practices or This Privacy Policy</h3>
            <p class="text-secondary font-weight-normal size15 decor">We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. If you have any questions about our Privacy Practices or this Policy, please contact us.
            </p>
        </div>
        
        
        
    </div>
</section>

<?php include_once "footer.php";?>




<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<?php include "libs2.php"; ?>


</body>
</html>