<?php
// require_once("maintenance.php");
// maintenance(TRUE);
?>
<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title>Success Stories | Find Affordable Legal Help with us </title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />

<meta name="description" content="Enjoy Fast Access To Top Family Lawyers Across The US. Connect Now With An Attorney In Your Local Area And Get Your Questions Answered Now.">
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">

<?php include "libs.php"; ?>

<style>

#form32{
	display:none;
}

#head1{
	display:none;
}

li {
    border-bottom: 0px solid rgba(39, 40, 41, 0.2);
    padding: 0px;
}

ul {
    padding: 20px;
}




div.stars {
  display: inline-block;
}

input.star { display: none; }

label.star {
  float: right;
  padding: 1px;
  font-size: 20px;
  color: #444;
  /* transition: all .1s; */
}

input.star:checked ~ label.star:before {
  content: '\f005';
  color: #FD4;
  /* transition: all .15s; */
}

input.star-5:checked ~ label.star:before {
  color: #FE7;
  /* text-shadow: 0 0 20px #952; */
}

input.star-1:checked ~ label.star:before { color: #F62; }

label.star:hover { transform: rotate(-10deg) scale(1.3); }

label.star:before {
  content: '\f006';
  font-family: FontAwesome;
}



/* Large devices (laptops/desktops, 992px and up) */
/* @media only screen and (min-width: 992px) {}  */

/* Extra large devices (large laptops and desktops, 1200px and up) */
/* @media only screen and (min-width: 1200px) {} */


</style>




<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>


</head>


<body class="single-page contact-page" style="font-family:'Trebuchet MS', Helvetica, sans-serif";>

<?php include_once "header.php"; ?>
<?php 
$database=new Database();

$db = $database->getConnection();
            
if (isset($_POST['submitbtn']))
{
    $Name=$_POST['fname'];
    $Email=$_POST['email'];
    $Rating=$_POST['rating'];
    $Review=$_POST['msg'];
    $Date=date("M d, Y");

    
     //write query
     $query = "INSERT INTO
            success_stories
    SET
    Name=:Name, Email=:Email, Rating=:Rating,  Review=:Review, Date=:Date";

    $stmt = $db->prepare($query);

    // posted values
    $Name=htmlspecialchars(strip_tags($Name));
    $Email=htmlspecialchars(strip_tags($Email));
    $Rating=htmlspecialchars(strip_tags($Rating));
    $Review=htmlspecialchars(strip_tags($Review));
    $Date=htmlspecialchars(strip_tags($Date));
    // bind values 
    $stmt->bindParam(":Name", $Name);
    $stmt->bindParam(":Email", $Email);
    $stmt->bindParam(":Rating", $Rating);
    $stmt->bindParam(":Review", $Review);
    $stmt->bindParam(":Date", $Date);
    if($stmt->execute()){
        // echo "succes";
        
          }else{

    }
}
    
    ?>

<div class="jumbotron jumbotron-fluid bg1 stories_bg border-0">
    <div class="paddings">
        <h1 class="size46 text-white text-center ">CLIENT STORIES</h1>
    </div>
</div>

<!-- <h1>Heading 1 (36px)</h1>
  <h2>Heading 2 (30px)</h2>
  <h3>Heading 3 (24px)</h3>
  <h4>Heading 4 (20px)</h4>
  <h5>Heading 5 (18px)</h5>
  <h6>Heading 6 (16px)</h6> -->

<div class="pl-4">
    <input type="button" class="btn btn-primary" value="Create your own review" onclick="showDiv12()" id="btn1"/>
</div>


<section class="container-fluid text-left text-dark mt-5" id="form32">

    <div class="col-lg-6 col-md-8 col-sm-12 col-12 d-block">
        <p class="text-dark font-weight-bold mb-2">Submit your review</p>

        <form class="success_stories" method="post" >

            <div class="form-group mb-1">
                <label class="font-weight-bold mb-0 ml-1 mt-2 size13" >Name:</label>
                <input type="text" class="form-control p-3" name="fname" id="fname"  style="border-radius:0px;"/> 
            </div>

            <div class="form-group mb-1">
                <label class="font-weight-bold mb-0 ml-1 mt-2 size13" >Email:</label>
                <input type="text" class="form-control p-3" name="email" id="email" style="border-radius:0px;"/>
            </div>

            <div class="form-group mb-1">
                <label class="font-weight-bold mb-0 ml-1 mt-2 size13">Rating:</label><br>
                <div class="stars text-left">
                    <input class="star star-5" id="star-5" type="radio" name="rating" value="5"/>
                    <label class="star star-5 mb-0" for="star-5"></label>

                    <input class="star star-4" id="star-4" type="radio" name="rating" value="4"/>
                    <label class="star star-4 mb-0" for="star-4"></label>

                    <input class="star star-3" id="star-3" type="radio" name="rating" value="3"/>
                    <label class="star star-3 mb-0" for="star-3"></label>

                    <input class="star star-2" id="star-2" type="radio" name="rating" value="2"/>
                    <label class="star star-2 mb-0" for="star-2"></label>

                    <input class="star star-1" id="star-1" type="radio" name="rating" value="1"/>
                    <label class="star star-1 mb-0" for="star-1"></label>
                </div>
            </div>

            <div class="form-group">
                <label class="font-weight-bold mb-0 ml-1 mt-2 size13" >Review:</label>
                <textarea class="form-control p-3" name="msg" id="msg" rows="8" cols="70" style="border-radius:0px;"></textarea>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Submit" name="submitbtn" class="btn btn-md btn-success mr-2 rounded-0"  />
                <input type="button" class="btn btn-secondary rounded-0" value="Cancel" onclick="showDiv21()"/>
            </div>
        </form>
    </div>
        
</section>


<div class="container-fluid mb-0 pb-0">
            
    <?php
        $database=new Database();
        $db = $database->getConnection();
        $sql = "SELECT * from  success_stories ";
        $query = $db -> prepare($sql);
        $query->execute();
    ?>
    <hr class="mt-4 ml-3 mr-3" style="border: 0.5px dashed #a2a2a2;" />
    <p class="font-weight-light font-italic text-dark mb-2 ml-3 font3 size13">Affordable Legal Help</p>
    <p class="font-weight-light font-italic text-dark mb-2 ml-3 font3 size13">Average rating:  <?php echo htmlentities($query->rowCount());?> reviews</p>

</div>

<div class="container-fluid mb-5">
        
    <table id="zctb" class="table table-white table-borderless p-0 m-0">

    <thead id="head1">
        <tr>
            <th class="text-white"> no use</th>
        </tr>
    </thead>
    <tbody>


        <?php
            $database=new Database();
            $db = $database->getConnection();

            $sql = "SELECT * from  success_stories ";
            $query = $db -> prepare($sql);
            $query->execute();
            $results=$query->fetchAll(PDO::FETCH_OBJ);
            $cnt=1;
            $opt="";
            if($query->rowCount() > 0)
            {
                foreach($results as $result)
                {		
        ?>	

        <tr>
            <td>
                <hr class="mt-4" style="border: 0.5px dashed #a2a2a2;" />

                <?php  
                    if ($result->Rating == 1 ) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    } elseif ($result->Rating == 2) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    } elseif ($result->Rating == 3) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    }elseif ($result->Rating == 4) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    }elseif ($result->Rating == 5) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                    }else {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                    }
                ?>
<!-- 
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="far fa-star text-warning inline-block"></i> -->

                <p class="font-weight-light font-italic text-dark mb-2" style="font-size:12px; display: inline-block; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;"> <?php echo htmlentities($result->Date);?> by <?php echo htmlentities($result->Name);?> on Affordable Legal Help</p>
                
                <div class="card border-right-0 border-top-0 border-bottom-0 rounded-0" style="border-left: 5px solid rgba(222, 222, 222);" >
                    <div class="card-body pt-3 pb-3">
                        <p class="card-text text-black-50 font3 size15"><?php echo htmlentities($result->Review);?></p>
                    </div>
                </div>
            </td>
        </tr>
        <?php }} ?>
        <!-- <tr>
            <td>
                <hr class="mt-4" style="border: 0.5px dashed #a2a2a2;" />


                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="far fa-star text-warning inline-block"></i>

                <p class="font-weight-light font-italic text-dark mb-2" style="font-size:12px; display: inline-block; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;">Nov 26, 2019 by Daniel Rivas on Affordable Legal Help</p>
                
                <div class="card border-right-0 border-top-0 border-bottom-0 rounded-0" style="border-left: 5px solid rgba(222, 222, 222);" >
                    <div class="card-body pt-3 pb-3">
                        <p class="card-text text-black-50" style="font-size:14px; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;">Going through formal proceedings of filing divorce is extremely frustrating. Highly skilled unbundled lawyers under Affordable legal Help will ensure that your goals and demands are met without breaking your bank.</p>
                    </div>
                </div>
            </td>
        </tr> -->

        

    </tbody>
    </table>
</div>



<?php include_once "footer.php"; ?>



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>

<!--#Libraries file#-->
<?php include "libs2.php"; ?>
<script async src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<script defer src="client_validate.js?v=10"></script>




<script defer src="http://www.radioactivethinking.com/rateit/src/jquery.rateit.js"></script>



<script defer src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script defer src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>




</body>
</html>
